import type { Config } from 'tailwindcss';

// Design tokens sourced from the Stitch project's design system ("Penumbra Technical
// Standard" retro B&W pixel variant, confirmed 2026-07-07 as the authoritative direction).
// Content globs cover the route stubs and any screens imported from Google Stitch.
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'slate-wire': '#ffffff',
        'surface-tint': '#ffffff',
        'status-proven': '#ffffff',
        'tertiary-fixed': '#ffffff',
        'on-tertiary-fixed-variant': '#000000',
        'on-secondary': '#000000',
        'on-primary': '#000000',
        tertiary: '#ffffff',
        'surface-container-lowest': '#000000',
        'inverse-primary': '#000000',
        'on-secondary-fixed-variant': '#000000',
        'inverse-surface': '#ffffff',
        'surface-container': '#000000',
        'primary-container': '#000000',
        outline: '#ffffff',
        'on-background': '#ffffff',
        'text-muted': '#ffffff',
        surface: '#000000',
        'on-secondary-fixed': '#000000',
        'status-evaluated': '#ffffff',
        'secondary-fixed': '#ffffff',
        'surface-container-highest': '#000000',
        'on-primary-fixed-variant': '#000000',
        'fog-alpha': 'rgba(255, 255, 255, 0.2)',
        'primary-fixed': '#ffffff',
        'on-primary-fixed': '#000000',
        background: '#000000',
        'on-tertiary-fixed': '#000000',
        'on-surface-variant': '#ffffff',
        'on-primary-container': '#ffffff',
        'on-tertiary-container': '#000000',
        'on-error': '#ffffff',
        'error-container': '#000000',
        'secondary-container': '#ffffff',
        'inverse-on-surface': '#000000',
        'surface-variant': '#000000',
        'tertiary-fixed-dim': '#ffffff',
        'surface-container-low': '#000000',
        'primary-fixed-dim': '#ffffff',
        'surface-container-high': '#000000',
        primary: '#ffffff',
        'surface-bright': '#000000',
        error: '#ffffff',
        secondary: '#ffffff',
        'obsidian-deep': '#000000',
        'on-surface': '#ffffff',
        'outline-variant': '#ffffff',
        'secondary-fixed-dim': '#ffffff',
        'on-error-container': '#000000',
        'surface-dim': '#000000',
        'on-secondary-container': '#000000',
        'tertiary-container': '#000000',
        'on-tertiary': '#000000',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
      spacing: {
        'container-max': '1440px',
        unit: '4px',
        'sidebar-width': '320px',
        gutter: '24px',
        'board-size-lg': '640px',
      },
      fontFamily: {
        'label-caps': ["'Press Start 2P'", 'monospace'],
        'headline-lg-mobile': ["'Press Start 2P'", 'monospace'],
        'data-mono': ["'Press Start 2P'", 'monospace'],
        'display-lg': ["'Press Start 2P'", 'monospace'],
        'body-lg': ["'Press Start 2P'", 'monospace'],
        'headline-sm': ["'Press Start 2P'", 'monospace'],
        'body-md': ["'Press Start 2P'", 'monospace'],
        'headline-md': ["'Press Start 2P'", 'monospace'],
      },
      fontSize: {
        'label-caps': ['10px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'data-mono': ['10px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'body-lg': ['14px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['12px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
