# Snapshots the Postgres DB and the calibration corpus input file so an
# unplanned shutdown (power loss, Docker Desktop crash, etc.) during the long
# calibration run never loses more than one backup interval's worth of work.
#
# The DB itself is WAL-crash-safe and the calibration run is resumable (it
# checks fog_scores before re-scoring), so the real single point of failure
# this guards against is corpus\calibration\positions.jsonl -- it's gitignored
# (see docs/FOG_INDEX_METHODOLOGY.md) and not guaranteed byte-reproducible if
# regenerated, since it's built from live Lichess game history.
#
# Restore:
#   docker cp backups\penumbra_<stamp>.dump penumbra-postgres:/tmp/restore.dump
#   docker exec penumbra-postgres pg_restore -U penumbra -d penumbra --clean --if-exists /tmp/restore.dump
#   Copy-Item backups\positions_<stamp>.jsonl corpus\calibration\positions.jsonl
#
# Registered as an hourly Windows scheduled task ("PenumbraCalibrationBackup");
# safe to run manually too.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$backupDir = Join-Path $repoRoot 'backups'
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null

$stamp = Get-Date -Format 'yyyyMMdd_HHmmss'

# --- Postgres dump (custom format, compressed) ---
# Dumped inside the container and pulled out via `docker cp` rather than
# piped through PowerShell stdout redirection, which re-encodes text and
# would corrupt pg_dump's binary custom-format output.
$containerDumpPath = '/tmp/penumbra_backup.dump'
docker exec penumbra-postgres pg_dump -U penumbra -Fc penumbra -f $containerDumpPath
if ($LASTEXITCODE -ne 0) {
    throw "pg_dump failed (exit $LASTEXITCODE) -- is penumbra-postgres running?"
}

$dumpFile = Join-Path $backupDir "penumbra_$stamp.dump"
docker cp "penumbra-postgres:$containerDumpPath" $dumpFile
if ($LASTEXITCODE -ne 0) {
    throw "docker cp of the dump failed (exit $LASTEXITCODE)"
}
docker exec penumbra-postgres rm -f $containerDumpPath

# --- Calibration corpus input (not tracked in git; can't be regenerated byte-identical) ---
$corpusSrc = Join-Path $repoRoot 'corpus\calibration\positions.jsonl'
if (Test-Path $corpusSrc) {
    Copy-Item $corpusSrc (Join-Path $backupDir "positions_$stamp.jsonl") -Force
}

# --- Retention: keep the 48 most recent of each (~2 days at hourly cadence) ---
Get-ChildItem $backupDir -Filter 'penumbra_*.dump' | Sort-Object LastWriteTime -Descending | Select-Object -Skip 48 | Remove-Item -Force
Get-ChildItem $backupDir -Filter 'positions_*.jsonl' | Sort-Object LastWriteTime -Descending | Select-Object -Skip 48 | Remove-Item -Force

Write-Output "backup ok: $dumpFile"
